# Generated by Django 4.2 on 2023-07-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('fulltime_permanent', 'Fulltime Permanent'), ('fulltime_probation', 'Fulltime Probation'), ('part_time_contract', 'Part Time Contract')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='new_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new', to='performance.designation'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='new_salary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='past_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past', to='performance.designation'),
        ),
    ]
