# Generated by Django 4.2 on 2023-07-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_alter_promotion_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='new_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
