# Generated by Django 4.2 on 2023-07-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_promotion_bonus_alter_promotion_new_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='new_salary',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='past_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_position', to='performance.designation'),
        ),
    ]
