# Generated by Django 4.2 on 2023-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_remove_promotion_new_salary_alter_promotion_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
